"""add visit_number to visits

Revision ID: 504bcd3e91b8
Revises: fe00270ba9ca
Create Date: 2026-01-14 07:22:09.064960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '504bcd3e91b8'
down_revision: Union[str, Sequence[str], None] = 'fe00270ba9ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('visits', sa.Column('visit_number', sa.Integer(), nullable=True))

    # Populate visit_number for existing visits
    # Using ROW_NUMBER() to assign sequential numbers per child
    op.execute("""
        UPDATE visits
        SET visit_number = subquery.rn
        FROM (
            SELECT id, ROW_NUMBER() OVER (PARTITION BY child_id ORDER BY visit_date, id) as rn
            FROM visits
        ) as subquery
        WHERE visits.id = subquery.id
    """)

    # Now make the column non-nullable
    op.alter_column('visits', 'visit_number', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'visit_number')
    # ### end Alembic commands ###
