"""init schema

Revision ID: fe00270ba9ca
Revises: 
Create Date: 2026-01-12 22:15:22.597001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe00270ba9ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pseudo_id', sa.String(length=64), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('sex', sa.String(length=16), nullable=False),
    sa.Column('clinic_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_children_pseudo_id'), 'children', ['pseudo_id'], unique=True)
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('age_months', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_child_id'), 'visits', ['child_id'], unique=False)
    op.create_table('ml_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('asd_risk_bucket', sa.String(length=16), nullable=False),
    sa.Column('explanations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_predictions_visit_id'), 'ml_predictions', ['visit_id'], unique=True)
    op.create_table('questionnaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('regression', sa.Boolean(), nullable=False),
    sa.Column('seizures', sa.Boolean(), nullable=False),
    sa.Column('motor_delay', sa.Boolean(), nullable=False),
    sa.Column('global_delay', sa.Boolean(), nullable=False),
    sa.Column('family_history_asd_ndd', sa.Boolean(), nullable=False),
    sa.Column('dysmorphic_features', sa.Boolean(), nullable=False),
    sa.Column('macrocephaly', sa.Boolean(), nullable=False),
    sa.Column('microcephaly', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaires_visit_id'), 'questionnaires', ['visit_id'], unique=True)
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('storage_path', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_task_type'), 'videos', ['task_type'], unique=False)
    op.create_index(op.f('ix_videos_visit_id'), 'videos', ['visit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_visit_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_task_type'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_questionnaires_visit_id'), table_name='questionnaires')
    op.drop_table('questionnaires')
    op.drop_index(op.f('ix_ml_predictions_visit_id'), table_name='ml_predictions')
    op.drop_table('ml_predictions')
    op.drop_index(op.f('ix_visits_child_id'), table_name='visits')
    op.drop_table('visits')
    op.drop_index(op.f('ix_children_pseudo_id'), table_name='children')
    op.drop_table('children')
    # ### end Alembic commands ###
